---

# Comment in to build Alpaca from source
 alpaca_from_source: yes
 alpaca_version: dev
 alpaca_clone_directory: /opt/alpaca

 triplestore_namespace: islandora
 alpaca_triplestore_base_url: http://localhost:8080/bigdata
 alpaca_milliner_base_url: http://localhost:80/milliner
 alpaca_gemini_base_url: http://localhost:80/gemini
 alpaca_houdini_base_url: http://localhost:80/houdini
 alpaca_homarus_base_url: http://localhost:80/homarus
